### ISSUE TITLE
Special types for certain matrix shapes

### ISSUE THREAD

**Issue by amigalemming** [haskell-numerics/hmatrix#128]
It would be nice to have not only a generic matrix type, but also special matrix types:
Matrix.Square, Matrix.Banded, Matrix.Diagonal, Matrix.Symmetric, Matrix.Hermitian, Matrix.LowerTriang, Matrix.UpperTriang, Matrix.Householder, Matrix.Givens. In applications the type of a matrix is usually known at compile time and the different types add a new level of type safety. This would be a level of type-strictness between `Numeric.LinearAlgebra.Matrix` and `Numeric.LinearAlgebra.Static.L`. It would be simpler to check than `Static.L` stuff, but should be quite expressive. E.g. Matrix.Square would be required for matrix inversion, transposition would flip between Matrix.LowerTriang and Matrix.UpperTriang and would be the identity function on Matrix.Symmetric. Matrix.LowerTriang would allow for a fast determinant implementation. luPacked could return a special type Matrix.LowerUpperTriang that can be passed to luSolve or can be used to extract Matrix.LowerTriang or Matrix.UpperTriang. It would eliminate the danger of treating the result of luPacked like an ordinary matrix. The different matrix types could use internally optimized storage schemes.

Maybe we need a matrix type with phantom type parameters for square dimensions or symmetricity in order to reduce combinatorial explosion of types. I am uncertain about that.

This would also nicely work together with #127.

**Comment by albertoruiz** [comment]
Yes, I fully agree. Special matrix types are needed both for efficiency and safety. From a long time ago my idea was that a version called 1.x will be released when a basic set of these special matrix types is ready and can be combined in a simple way. I am not sure if a sum type or different types is the best option, but we can experiment with different approaches.

**Comment by amigalemming** [comment]
I implemented my proposal in a new package named [lapack](https://hackage.haskell.org/package/lapack).
