### ISSUE TITLE
Crash from usage of static diagR with <>

### ISSUE THREAD

**Issue by mstksg** [haskell-numerics/hmatrix#251]
I'll be looking into this myself, just filing an issue to have this be recorded.

```haskell
> x = diagR 0 (vec 1 2 3) :: L 5 3
> y = x <> (1 :: L 3 3)
> :t y
y :: L 5 3
> z = (1 :: L 5 5) <> y
> :t z
z :: L 5 3
> z
*** Exception: inconsistent dimensions in matrix product (5, 5) x (3, 3)
```

It seems to come from `y` being treated internally as a 3x3 matrix, despite its type indicating it should be 5x3.

**Comment by HuwCampbell** [comment]
The issue is [here](https://github.com/haskell-numerics/hmatrix/blob/a4c96a89a88bafe49b98ed84d8999eb46cb01f81/packages/base/src/Numeric/LinearAlgebra/Static.hs#L630).

When we call toDiag
```haskell
mulR (isDiag -> Just (0,a,_)) (extract -> b) = mkL (asColumn a * takeRows (LA.size a) b)
```
The wildcard pattern contains the true number of rows; and asColumn and takeRows don't get it right.
