### ISSUE TITLE
Numeric.LinearAlgebra.Static.# appends single element when used with konst'd `R 0`

### ISSUE THREAD

**Issue by mstksg** [haskell-numerics/hmatrix#263]
Will be looking into this myself, but I'm just leaving a note here for reference and to keep track of this :)

```haskell
> (1 :: R 3) # (2 :: R 0)      -- aka (konst 2 :: R 0)
-- expected
[1, 1, 1] :: R 3
-- actual:
[1, 1, 1, 2] :: R 3
```

The issue does not show up when creating an `R 0` with a method other than `konst`.

**Comment by HuwCampbell** [comment]
This looks fixed to me. Closing.
