### ISSUE TITLE
Release `0.19.0.0` isn't tagged on github

### ISSUE THREAD

**Issue by regnat** [haskell-numerics/hmatrix#280]
All the releases of `hmatrix` on hackage seem to correspond to a tag on the git repository, but `0.19.0.0` isn't tagged which makes comparing the code to other versions much more painful since I don't know which commit it corresponds to

**Comment by idontgetoutmuch** [comment]
There is now a tag of 0.20.0.0 at https://github.com/haskell-numerics/hmatrix-sundials. I don't know how to tag retrospectively. I am closing this but let me know if there is something more you would like me to do.
