### ISSUE TITLE
Numeric.LinearAlgebra.Static: Need for constraint 1 <= n on input to LA.&

### ISSUE THREAD

**Issue by martin-neuhaeusser** [haskell-numerics/hmatrix#290]
Extending a vector `x :: R n` by a `d :: Double` to produce an `y :: R (n + 1)` can be done either by
`y = x LA.& d` or by `y = x LA.# ((LA.konst d) :: R 1)` (where `LA` denotes Numeric.LinearAlgebra.Static).

However, `LA.&` requires the constraint `KnownNat n, 1 <= n` for the input vector type, whereas `LA.#` only requires `KnownNat n, KnownNat m` with `m` being fixed as `1` by the type annotation.
Are there any good reasons for this asymmetry? For me, having the additional `1 <= n` constraint on `LA.&` is rather annoying, as it pollutes large parts of my code for no (obvious) reason. Therefore I try to circumvent this by using `LA.#`, which feels rather clumsy.

Is there a technical need for having the `1<=n` constraint on `LA.&` , or could it be removed?

**Comment by idontgetoutmuch** [comment]
I know of no reason for the additional and apparently redundant constraint. Could you send a PR?
