### ISSUE TITLE
cabal-install hmatrix-tests used over 58 gb of memory before I killed it

### ISSUE THREAD

**Issue by GeorgeCo** [haskell-numerics/hmatrix#293]
cabal install hmatrix-tests used over 58 gb of memory before I killed it
 ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.4
macOS 10.14.4

**Comment by idontgetoutmuch** [comment]
Yes the whole test framework needs some love and attention.

**Comment by Magalame** [comment]
`stack install hmatrix-tests` went well on my 8Go laptop

**Comment by GeorgeCo** [comment]
@Magalame 
> `stack install hmatrix-tests` went well on my 8Go laptop

which version of ghc were you using?

**Comment by GeorgeCo** [comment]
on ghc 8.6.5 cabal install hmatrix-tests fails with 

[3 of 4] Compiling Numeric.LinearAlgebra.Tests ( src/Numeric/LinearAlgebra/Tests.hs, dist/build/Numeric/LinearAlgebra/Tests.p_o )
Simplifier ticks exhausted
  When trying UnfoldingDone $j_s1mHf
  To increase the limit, use -fsimpl-tick-factor=N (default 100).
   
  If you need to increase the limit substantially, please file a
  bug report and indicate the factor you needed.
   
  If GHC was unable to complete compilation even with a very large factor
  (a thousand or more), please consult the "Known bugs or infelicities"
  section in the Users Guide before filing a report. There are a
  few situations unlikely to occur in practical programs for which
  simplifier non-termination has been judged acceptable.
   
  To see detailed counts use -ddump-simpl-stats
  Total ticks: 4513444
cabal: Leaving directory '/var/folders/df/5d_dsdrx1dn4j30ktsgn8blh0000gp/T/cabal-tmp-3611/hmatrix-tests-0.19.0.0'
cabal: Error: some packages failed to install:
hmatrix-tests-0.19.0.0-CBikoZo0LFRBCtRsbHuMzR failed during the building
phase. The exception was:
ExitFailure 1

Can anybody install it on ghc 8.6.5? Also fails if I install with tick-factor of 200. With tick factor of 1000 it was consuming over 50 gb of (virtual) memory before I killed it.

**Comment by GeorgeCo** [comment]
what version of ghc was that?

**Comment by Magalame** [comment]
For ghc corresponding to lts-10.9, also tried 12.14.
