### ISSUE TITLE
How to use floor(), and relu() with `R n`?

### ISSUE THREAD

**Issue by capn-freako** [haskell-numerics/hmatrix#305]
Has anyone figured out how to use either of the following functions with type: `R n`?

- `floor`

    Requires a `RealFrac` instance.

- `relu` (i.e. - `max 0`)

    Requires an `Ord` instance.

If so, could you post a working solution, please?

Thanks!

**Comment by mstksg** [comment]
Try `dvmap`:

```haskell
dvmap floor :: R n -> R n
dvmap (max 0) :: R n -> R n
```

**Comment by capn-freako** [comment]
That worked. Thanks!
