### ISSUE TITLE
doesn't install with ghc 8.8.1

### ISSUE THREAD

**Issue by GeorgeCo** [haskell-numerics/hmatrix#309]
ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.8.0.20190721
...
cabal install hmatrix
...
[ 7 of 27] Compiling Internal.Element ( src/Internal/Element.hs, dist/build/Internal/Element.o )

src/Internal/Element.hs:32:24: error:
    Module ‘Data.List.Split’ does not export ‘chunksOf’
   |
32 | import Data.List.Split(chunksOf)

**Comment by idontgetoutmuch** [comment]
I think there was a name change in the split package (or whatever it calls itself). Any chance of a PR?

**Comment by GeorgeCo** [comment]
I believe this is fixed now
