### ISSUE TITLE
Memory leaks in C code

### ISSUE THREAD

**Issue by HuwCampbell** [haskell-numerics/hmatrix#326]
Looking at the C code, a very common pattern is this:

```c
doublecomplex * workv = (doublecomplex*)malloc(n*sizeof(doublecomplex));
CHECK(!workv,MEM);
do_stuff(&work, &res);
CHECK(res,res);
free(workv);
OK
```

where `CHECK` and `OK` are macros which call return. There's an issue here in that if the calls to `CHECK` fail, none of the memory allocated will be freed (until the program exits completely).

**Comment by HuwCampbell** [comment]
Fixing this is pretty mechanical. I've fixed up a few by creating a macro `UNWIND`, which sets a return variable and jumps to a label where we will call free.

```c
    UNWIND(!work,MEM,done)
    do_stuff (&work, &res);
    UNWIND(res,res,cleanup)

cleanup:
    free(work);
done:
    return ret;
```

**Comment by HuwCampbell** [comment]
This is also effecting calls to solvers, so singular matrices under the linear solve family are leaking memory.

**Comment by idontgetoutmuch** [comment]
Fixed by https://github.com/haskell-numerics/hmatrix/pull/327
