### ISSUE TITLE
Error: On entry to DGEMM parameter number 13 had an illegal value

### ISSUE THREAD

**Issue by freckletonj** [haskell-numerics/hmatrix#353]
I'm trying the example from [here](http://dis.um.es/~alberto/hmatrix/static.html) and getting the following error:

```haskell
Main> a <> b

** On entry to DGEMM  parameter number 13 had an illegal value
(matrix
 [  1.400618532456e-312,  1.40054567967e-312, 6.9353431094709e-310
 , 6.9353431094709e-310, 1.400545650416e-312,   1.40054370068e-312 ] :: L 2 3)
```

I'm trying to use this within a nix environment, but I'm honestly not sure how BLAS library is getting linked, nor where from. If I remove `openblas` from my nix environment, HMatrix still seems to find _some_ BLAS library, though apparently it's not the right one.

Whether I include openblas or not - I don't know if it's related - I also get this warning:

```sh
<no location info>: warning: [-Wmissed-extra-shared-lib]
    libblas.so: cannot open shared object file: No such file or directory
    It's OK if you don't want to use symbols from it directly.
    (the package DLL is loaded by the system linker
     which manages dependencies by itself).

<no location info>: warning: [-Wmissed-extra-shared-lib]
    liblapack.so: cannot open shared object file: No such file or directory
    It's OK if you don't want to use symbols from it directly.
    (the package DLL is loaded by the system linker
     which manages dependencies by itself).
```

I'm on Debian, inside nix-shell using `callCabal2nix`, using ghc884, and the following nixpkgs:
```sh
nixpkgs-src = builtins.fetchTarball {
    url = "https://github.com/NixOS/nixpkgs/archive/fcc81bc974fabd86991b8962bd30a47eb43e7d34.tar.gz";
    sha256 = "1ysjmn79pl7srlzgfr35nsxq43rm1va8dqp60h09nlmw2fsq9zrc";
  };
```

**Comment by HuwCampbell** [comment]
There are a few flags which need to be passed when building on nix; "-fdisable-default-paths" ane "-fopenblas". If you're not using those it's possible its picking up the system default from Debian instead.

**Comment by freckletonj** [comment]
thanks! Sometimes it works, then it stops, randomly, and I don't actually know which library it pulls in. Should `update-alternatives ...` show the `/nix/...` version of libblas? Because it doesn't show up there for me.

Anyway, it's pretty fuzzy for me what's broken, so I'm just gonna close this. Thanks for your help!
