### ISSUE TITLE
Missing (or bad) C libraries: blas, lapack

### ISSUE THREAD

**Issue by thermohyaena** [haskell-numerics/hmatrix#374]
![Screenshot 2024-03-21 231735](https://github.com/haskell-numerics/hmatrix/assets/163030245/dc652e62-c128-4eba-8499-80d88ff0d16d)
Couldn't install hmatrix due to issue in the picture

![image](https://github.com/haskell-numerics/hmatrix/assets/163030245/14165109-66c2-4a52-837f-41c6a966d7ef)
What should be written in the "package:" section?

**Comment by thermohyaena** [comment]
![image](https://github.com/haskell-numerics/hmatrix/assets/163030245/bce7a049-534c-45f6-a455-3f7bf33fcfee)
This setup on stack.yaml wouldn't work

**Comment by stla** [comment]
See the [instructions here](https://github.com/haskell-numerics/hmatrix/blob/master/INSTALL.md#windows-10).

**Comment by thermohyaena** [comment]
> See the [instructions here](https://github.com/haskell-numerics/hmatrix/blob/master/INSTALL.md#windows-10).
> 

Ah I have solved this issue by putting nothing on the package section and add openblas flag in stack.yaml, and put hmatrix under dependence in package.ymal

**Comment by thermohyaena** [comment]
What I'm currently encountering is that it always outputs the error of "module/package not found" when I write import XXX in .hs file including Lib modules from src folder.

However, importing these modules works in ghci, but not in .hs

**Comment by stla** [comment]
Sorry, I don't see what you mean.

**Comment by thermohyaena** [comment]
> Sorry, I don't see what you mean.

What i mean is basic in the pictures below that
![Screenshot 2024-03-25 111236](https://github.com/haskell-numerics/hmatrix/assets/163030245/107643ef-dcad-4d70-8269-790219d6c089)

If i write import in .hs file, it pops error saying no module found for "Lib" and "import Numeric.LinearAlgebra ( (><), linearSolve )". Also i got error saying ambiguous type.

However,

![Screenshot 2024-03-25 111411](https://github.com/haskell-numerics/hmatrix/assets/163030245/6179e735-4f46-49b4-9230-ffbbea5b485a)

If i import it only in ghci, that works just fine

**Comment by thermohyaena** [comment]
btw I got this when i print the type of c in ghci, not sure if that's normal
Prelude Numeric.LinearAlgebra> :t c
c :: (Foreign.Storable.Storable a, Fractional a) => hmatrix-0.20.2:Internal.Matrix.Matrix a

**Comment by stla** [comment]
Did you build the package (`stack build`)? Otherwise it's normal that the module is not found in VS code yet.

**Comment by thermohyaena** [comment]
> Did you build the package (`stack build`)? Otherwise it's normal that the module is not found in VS code yet.

Yeah I have tried that, nothing changes unfortunately

Despite the error showing, it would still work for imported packages, and Lib would still be imported by the main exec file tho.

What I'm more concerned about is actually the type of matrix, the one I get from :t in ghc looks a bit weird?

Prelude Numeric.LinearAlgebra> :t c
c :: (Foreign.Storable.Storable a, Fractional a) => hmatrix-0.20.2:Internal.Matrix.Matrix a

**Comment by stla** [comment]
I don't find this type is weird.

For your other problem, unfortunately we are off-topic here. This is not related to `hmatrix`. You could open a question on StackOverflow or Haskell discourse.

**Comment by thermohyaena** [comment]
> I don't find this type is weird.
> 
> For your other problem, unfortunately we are off-topic here. This is not related to `hmatrix`. You could open a question on StackOverflow or Haskell discourse. 

Yeah right, thanks for your help!
